#!/bin/sh

check_all_packages git curl vim zsh htop nodejs nodejs-legacy tmux \
  exuberant-ctags silversearcher-ag imagemagick \
  libxslt1-dev libcurl4-openssl-dev libksba8 libksba-dev libqtwebkit-dev libreadline-dev \
  libsqlite3-dev sqlite3 postgresql postgresql-server-dev-all redis-server \

