#!/bin/sh

if !(asdf list ruby > /dev/null); then
  asdf plugin-add ruby
fi

if !(asdf list python > /dev/null); then
  asdf plugin-add python
fi

if !(asdf list nodejs > /dev/null); then
  asdf plugin-add nodejs
fi

find_latest() {
  asdf list-all $1 | grep -v - | tail -1 | sed -e 's/^ *//'
}

os="$(uname)"

ruby_version="$(find_latest ruby)"
if !(asdf list ruby | grep "$ruby_version" > /dev/null); then
  # Pre tasks
  case $os in
  Linux)
    # Ensure system deps are installed
    sudo apt-get build-dep -y ruby2.2
    number_of_cores=$(nproc)
    ;;
  Darwin)
    number_of_cores=$(sysctl -n hw.ncpu)
    ;;
  esac

  asdf install ruby "$ruby_version"

  # Post tasks
  gem update --system
  gem install bundler --no-document --pre

  bundle config --global jobs $((number_of_cores - 1))

  case $os in
  Linux)
    ;;
  Darwin)
    # bundle config build.libv8 --with-system-v8
    # bundle config build.therubyracer --with-v8-dir=/usr/local/opt/v8
    bundle config build.nokogiri --use-system-libraries --with-xml2-include=/usr/local/opt/libxml2/include/libxml2
    ;;
  esac
fi

python_version="$(find_latest python)"
if !(asdf list python | grep "$python_version" > /dev/null); then
  # Pre tasks
  case $os in
  Linux)
    ;;
  Darwin)
    export LDFLAGS="-L/usr/local/opt/zlib/lib"
    export CPPFLAGS="-I/usr/local/opt/zlib/include"
    export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"
    ;;
  esac

  asdf install python "$python_version"
fi

