#!/bin/sh

if !(asdf list ruby > /dev/null); then
  asdf plugin-add ruby
fi

find_latest_ruby() {
  asdf list-all ruby | grep -v - | tail -1 | sed -e 's/^ *//'
}

ruby_version="$(find_latest_ruby)"

if !(asdf list ruby | grep "$ruby_version" > /dev/null); then
  os="$(uname)"

  # Pre tasks
  case $os in
  Linux)
    # Ensure system deps are installed
    sudo apt-get build-dep -y ruby2.2
    number_of_cores=$(nproc)
    ;;
  Darwin)
    number_of_cores=$(sysctl -n hw.ncpu)
    ;;
  esac

  asdf install ruby "$ruby_version"

  # Post tasks
  gem update --system
  gem install bundler --no-document --pre

  bundle config --global jobs $((number_of_cores - 1))

  case $os in
  Linux)
    ;;
  Darwin)
    # bundle config build.libv8 --with-system-v8
    # bundle config build.therubyracer --with-v8-dir=/usr/local/opt/v8
    bundle config build.nokogiri --use-system-libraries --with-xml2-include=/usr/local/opt/libxml2/include/libxml2
    ;;
  esac
fi

