#!/bin/sh

git_clone_or_update "$HOME/.rbenv/plugins/bundler" "https://github.com/carsomyr/rbenv-bundler.git"
git_clone_or_update "$HOME/.rbenv/plugins/rbenv-gem-rehash" "https://github.com/sstephenson/rbenv-gem-rehash.git"
git_clone_or_update "$HOME/.rbenv/plugins/ruby-build" "https://github.com/sstephenson/ruby-build.git"

ruby_version="$(curl -sSL http://ruby.thoughtbot.com/latest)"

if !(rbenv versions | grep "$ruby_version" > /dev/null); then
  # Ensure system deps are installed
  sudo apt-get build-dep -y ruby2.2

  rbenv install -s "$ruby_version"
  rbenv global "$ruby_version"
  rbenv rehash

  gem update --system
  gem install bundler --no-document --pre

  number_of_cores=$(nproc)
  bundle config --global jobs $((number_of_cores - 1))
fi

