#!/bin/sh

check_all_packages git git-flow curl vim zsh htop glances nmon tmux cmake \
  exuberant-ctags silversearcher-ag fasd imagemagick llvm xz-utils tk-dev \
  libxslt1-dev libcurl4-openssl-dev libksba8 libksba-dev libqtwebkit-dev libreadline-dev \
  zlib1g-dev libbz2-dev libffi-dev liblzma-dev libncurses5-dev libncursesw5-dev python-openssl \
  libsqlite3-dev sqlite3 postgresql postgresql-server-dev-all redis-server

