tap 'thoughtbot/formulae'
tap 'homebrew/services'
tap 'homebrew/x11'
tap 'neovim/neovim'
cask_args appdir: '/Applications'

# Libs
brew 'openssl'
brew 'libxml2'

# Tools
brew 'ctags'
brew 'git'
brew 'rcm'
brew 'xz', args: ['universal']
brew 'the_silver_searcher'
brew 'tmux', args: ['HEAD']
brew 'zsh'
brew 'htop'
brew 'nmap'
brew 'ipcalc'
brew 'unrar'

# Clients
brew 'hub'
brew 's3cmd'
brew 'awscli'
brew 'aws-shell'
cask 'xquartz'
brew 'freerdp'
brew 'syncthing', restart_service: :changed
brew 'mas'
cask 'tunnelblick'
cask 'adium'
brew 'weechat', args: ['--with-aspell', '--with-curl', '--with-python', '--with-perl', '--with-ruby', '--with-lua', '--with-guile']
cask 'java' # required for squirrelsql
cask 'squirrelsql'

# Image manipulation
brew 'imagemagick'

# Testing
brew 'qt'

# Development
brew 'libyaml' # should come after openssl
brew 'node'
brew 'python'
brew 'python3'
brew 'neovim'

# Virtualization
brew 'xhyve', args: ['HEAD']
cask 'virtualbox', restart_service: :changed
cask 'vagrant'

# Databases
brew 'postgresql'
brew 'redis'
brew 'freetds'

# Utilities
brew 'reattach-to-user-namespace'
brew 'gnupg2'
brew 'gpg-agent'
mas 'LastPass', id: 926036361
cask 'google-chrome'
cask 'firefox'
cask 'adobe-reader'
cask 'mactex'
cask 'iterm2'
cask 'inkscape'
